default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails
  password: cafeehbom
  host: 206.189.190.11
  port: 5432

development:
  <<: *default
  database: find_my_coffee_caio_development

test:
  <<: *default
  database: find_my_coffee_caio_test

production:
  <<: *default
  database: find_my_coffee_production
  username: find_my_coffee
  password: <%= ENV['FIND_MY_COFFEE_DATABASE_PASSWORD'] %>
